NAME		=	replace

PATH_OBJS	=	./.OBJS/

SRC			= 	main.cpp

OBJS		=	$(addprefix $(PATH_OBJS), $(SRC:.cpp=.o))


CPPC		=	c++
CPPFLAGS	=	-Wall -Wextra -Werror -std=c++98
RM			=	rm -rf

all :		$(NAME)

$(NAME) :	$(OBJS) Makefile
			$(CPPC) $(OBJS) -o $(NAME)

$(PATH_OBJS)%.o :	%.cpp
					@mkdir -p $(PATH_OBJS)
					$(CPPC) $(CPPFLAGS) -c $< -o $@

bite :
			$(RM) $(PATH_OBJS)

fbite :		
			$(RM) $(PATH_OBJS) $(NAME)
			
re :		fbite all
			
.PHONY:		all bite fbite re
